version: 2

release:
  draft: false
  prerelease: true

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

  - id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0

  - id: windows
    goos: [windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

  - id: freebsd
    goos: [freebsd]
    goarch: [386, amd64]
    env:
      - CGO_ENABLED=0

archives:
  - <<: &archives_defaults
      files:
        - README.md
        - LICENSE
    id: nix
    builds: [macos, linux, freebsd]
    format: tar.gz
  - <<: *archives_defaults
    id: windows
    builds: [windows]
    format: zip

changelog:
  disable: true
